# https://github.com/DavidAnson/markdownlint/
# Line length
MD013:
  line_length: 1280
  code_blocks: false
  tables: false

# Multiple headings with the same content
MD024:
  siblings_only: true

# Inline HTML
MD033: false
