repos:
  - repo: https://github.com/StorageMatt/pre-commit
    rev: 1.0.0
    hooks:
      - id: update_tool_versions
      - id: sort_tf_vars
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__.tflint.hcl
      - id: terraform_tfsec
        args:
          - >
            --args=--no-module-downloads
            --exclude-downloaded-modules
      - id: terraform_trivy
        args:
          - >
            --args=--skip-dirs="**/.terragrunt-cache,**/.terraform"
            --ignorefile="__GIT_WORKING_DIR__/.trivyignore"
            --tf-exclude-downloaded-modules
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
